// app/routes/contact.tsx
import { useState } from "react";
import { Form, useActionData, useNavigation } from "react-router";
import type { Route } from "./+types/contact";
import { Layout } from "../components/Layout";
import { z } from "zod";

// Form validation schema
const contactSchema = z.object({
  name: z.string().min(2, "Name must be at least 2 characters"),
  email: z.string().email("Invalid email address"),
  subject: z.string().min(3, "Subject must be at least 3 characters"),
  message: z.string().min(10, "Message must be at least 10 characters"),
});

export async function action({ request }: Route.ActionArgs) {
  const formData = await request.formData();
  const data = {
    name: formData.get("name"),
    email: formData.get("email"),
    subject: formData.get("subject"),
    message: formData.get("message"),
  };

  // Validate form data
  const validation = contactSchema.safeParse(data);
  if (!validation.success) {
    return {
      success: false,
      errors: validation.error.flatten().fieldErrors,
    };
  }

  try {
    // TODO: Implement Cloudflare Email Worker
    // For now, we'll just log it (you'll need to set up Cloudflare Email Routing)
    console.log("Contact form submission:", validation.data);

    // In production, you would send email via Cloudflare Email Worker:
    // await sendEmail({
    //   to: process.env.CONTACT_EMAIL_TO,
    //   subject: `Portfolio Contact: ${validation.data.subject}`,
    //   body: `Name: ${validation.data.name}\nEmail: ${validation.data.email}\n\n${validation.data.message}`,
    // });

    return { success: true };
  } catch (error) {
    return {
      success: false,
      errors: { _form: ["Failed to send message. Please try again."] },
    };
  }
}

export function meta({}: Route.MetaArgs) {
  return [
    { title: "Contact - Chris Loidolt" },
    { name: "description", content: "Get in touch to discuss your project or collaboration opportunities." },
    { property: "og:title", content: "Contact - Chris Loidolt" },
    { property: "og:description", content: "Get in touch to discuss your project or collaboration opportunities." },
    { name: "twitter:title", content: "Contact - Chris Loidolt" },
    { name: "twitter:description", content: "Get in touch to discuss your project or collaboration opportunities." },
  ];
}

export default function Contact() {
  const actionData = useActionData<typeof action>();
  const navigation = useNavigation();
  const isSubmitting = navigation.state === "submitting";

  return (
    <Layout>
      <div className="max-w-2xl space-y-8">
        {/* Page Header */}
        <div>
          <div className="text-terminal-cyan text-sm mb-2">$ mail contact@chrisloidolt.com</div>
          <p className="text-terminal-gray text-sm">Compose your message below</p>
        </div>

        {/* Success Message */}
        {actionData?.success && (
          <div className="border-t border-terminal-green pt-6">
            <div className="text-terminal-green mb-2 text-sm">
              Message sent successfully
            </div>
            <p className="text-terminal-text text-sm">
              Thank you for reaching out. I'll get back to you soon.
            </p>
          </div>
        )}

        {/* Form */}
        <Form method="post" className="space-y-6">
          {/* Name Field */}
          <div>
            <label htmlFor="name" className="block text-terminal-cyan text-sm mb-2">
              name
            </label>
            <input
              type="text"
              id="name"
              name="name"
              required
              disabled={isSubmitting}
              className="w-full bg-terminal-darker border border-terminal-border p-3 text-terminal-text placeholder-terminal-gray focus:border-terminal-cyan focus:outline-none disabled:opacity-50 text-sm"
              placeholder="Your name"
            />
            {actionData?.errors?.name && (
              <div className="mt-2 text-terminal-red text-sm">
                {actionData.errors.name[0]}
              </div>
            )}
          </div>

          {/* Email Field */}
          <div>
            <label htmlFor="email" className="block text-terminal-cyan text-sm mb-2">
              email
            </label>
            <input
              type="email"
              id="email"
              name="email"
              required
              disabled={isSubmitting}
              className="w-full bg-terminal-darker border border-terminal-border p-3 text-terminal-text placeholder-terminal-gray focus:border-terminal-cyan focus:outline-none disabled:opacity-50 text-sm"
              placeholder="your.email@example.com"
            />
            {actionData?.errors?.email && (
              <div className="mt-2 text-terminal-red text-sm">
                {actionData.errors.email[0]}
              </div>
            )}
          </div>

          {/* Subject Field */}
          <div>
            <label htmlFor="subject" className="block text-terminal-cyan text-sm mb-2">
              subject
            </label>
            <input
              type="text"
              id="subject"
              name="subject"
              required
              disabled={isSubmitting}
              className="w-full bg-terminal-darker border border-terminal-border p-3 text-terminal-text placeholder-terminal-gray focus:border-terminal-cyan focus:outline-none disabled:opacity-50 text-sm"
              placeholder="What's this about?"
            />
            {actionData?.errors?.subject && (
              <div className="mt-2 text-terminal-red text-sm">
                {actionData.errors.subject[0]}
              </div>
            )}
          </div>

          {/* Message Field */}
          <div>
            <label htmlFor="message" className="block text-terminal-cyan text-sm mb-2">
              message
            </label>
            <textarea
              id="message"
              name="message"
              required
              disabled={isSubmitting}
              rows={8}
              className="w-full bg-terminal-darker border border-terminal-border p-3 text-terminal-text placeholder-terminal-gray focus:border-terminal-cyan focus:outline-none resize-none disabled:opacity-50 text-sm"
              placeholder="Type your message here..."
            />
            {actionData?.errors?.message && (
              <div className="mt-2 text-terminal-red text-sm">
                {actionData.errors.message[0]}
              </div>
            )}
          </div>

          {/* Form Error */}
          {actionData?.errors?._form && (
            <div className="text-terminal-red text-sm">
              {actionData.errors._form[0]}
            </div>
          )}

          {/* Submit Button */}
          <button
            type="submit"
            disabled={isSubmitting}
            className="text-terminal-cyan hover:text-terminal-text-bright transition-colors disabled:opacity-50 disabled:cursor-not-allowed text-sm"
          >
            {isSubmitting ? (
              <span className="flex items-center gap-2">
                <span className="terminal-cursor">_</span>
                <span>Sending...</span>
              </span>
            ) : (
              <span>$ send</span>
            )}
          </button>
        </Form>

        {/* Additional Contact Info */}
        <div className="border-t border-terminal-border pt-8">
          <div className="text-terminal-cyan text-sm mb-6">$ cat contact-info.txt</div>
          <div className="space-y-3 text-sm">
            <div className="flex items-center gap-4">
              <span className="text-terminal-gray w-20">email</span>
              <a
                href="mailto:contact@chrisloidolt.com"
                className="text-terminal-text hover:text-terminal-cyan transition-colors"
              >
                contact@chrisloidolt.com
              </a>
            </div>
            <div className="flex items-center gap-4">
              <span className="text-terminal-gray w-20">github</span>
              <a
                href="https://github.com/chris-loidolt"
                target="_blank"
                rel="noopener noreferrer"
                className="text-terminal-text hover:text-terminal-cyan transition-colors"
              >
                github.com/chris-loidolt
              </a>
            </div>
          </div>
        </div>
      </div>
    </Layout>
  );
}

// src/routes/contact/+page.svelte
<script lang="ts">
  import { enhance } from '$app/forms';
  import type { ActionData } from './$types';

  export let form: ActionData;

  let formData = {
    name: '',
    email: '',
    subject: '',
    message: '',
  };

  let isSubmitting = false;
</script>

<svelte:head>
  <title>Contact - Portfolio</title>
  <meta name="description" content="Get in touch to discuss your project or collaboration opportunities." />
</svelte:head>

<div class="max-w-2xl space-y-8">
  <!-- Page Header -->
  <div>
    <div class="text-sm mb-2" style="color: var(--accent-secondary)">Contact</div>
    <p class="text-base md:text-sm" style="color: var(--text-muted)">Send me a message using the form below</p>
  </div>

  <!-- Success Message -->
  {#if form?.success}
    <div class="pt-6" style="border-top: 1px solid var(--accent-primary)">
      <div class="mb-2 text-sm" style="color: var(--accent-primary)">
        Message sent successfully
      </div>
      <p class="text-sm" style="color: var(--text-primary)">
        Thank you for reaching out. I'll get back to you soon.
      </p>
    </div>
  {/if}

  <!-- Form Error -->
  {#if form?.error}
    <div class="pt-6" style="border-top: 1px solid var(--error-color)">
      <div class="mb-2 text-sm" style="color: var(--error-color)">
        Error
      </div>
      <p class="text-sm" style="color: var(--text-primary)">
        {form.error}
      </p>
    </div>
  {/if}

  <!-- Form -->
  <form method="POST" class="space-y-6" use:enhance={() => {
    isSubmitting = true;
    return async ({ update }) => {
      await update();
      isSubmitting = false;
    };
  }}>
    <!-- Name Field -->
    <div>
      <label for="name" class="block text-sm mb-2" style="color: var(--accent-secondary)">
        name
      </label>
      <input
        type="text"
        id="name"
        name="name"
        bind:value={formData.name}
        required
        minlength="2"
        class="input-terminal transition-all"
        disabled={isSubmitting}
      />
      {#if form?.errors?.name}
        <p class="mt-2 text-xs" style="color: var(--error-color)">
          {form.errors.name}
        </p>
      {/if}
    </div>

    <!-- Email Field -->
    <div>
      <label for="email" class="block text-sm mb-2" style="color: var(--accent-secondary)">
        email
      </label>
      <input
        type="email"
        id="email"
        name="email"
        bind:value={formData.email}
        required
        class="input-terminal transition-all"
        disabled={isSubmitting}
      />
      {#if form?.errors?.email}
        <p class="mt-2 text-xs" style="color: var(--error-color)">
          {form.errors.email}
        </p>
      {/if}
    </div>

    <!-- Subject Field -->
    <div>
      <label for="subject" class="block text-sm mb-2" style="color: var(--accent-secondary)">
        subject
      </label>
      <input
        type="text"
        id="subject"
        name="subject"
        bind:value={formData.subject}
        required
        minlength="3"
        class="input-terminal transition-all"
        disabled={isSubmitting}
      />
      {#if form?.errors?.subject}
        <p class="mt-2 text-xs" style="color: var(--error-color)">
          {form.errors.subject}
        </p>
      {/if}
    </div>

    <!-- Message Field -->
    <div>
      <label for="message" class="block text-sm mb-2" style="color: var(--accent-secondary)">
        message
      </label>
      <textarea
        id="message"
        name="message"
        bind:value={formData.message}
        required
        minlength="10"
        rows="6"
        class="input-terminal transition-all resize-y min-h-[120px]"
        disabled={isSubmitting}
      />
      {#if form?.errors?.message}
        <p class="mt-2 text-xs" style="color: var(--error-color)">
          {form.errors.message}
        </p>
      {/if}
    </div>

    <!-- Submit Button -->
    <div class="pt-4">
      <button
        type="submit"
        class="btn-terminal px-6 py-3 transition-opacity"
        disabled={isSubmitting}
        style={isSubmitting ? 'opacity: 0.5; cursor: not-allowed;' : ''}
      >
        {isSubmitting ? '[sending...]' : '[send message →]'}
      </button>
    </div>
  </form>
</div>
