// src/app/projects/page.tsx
import { Metadata } from 'next';
import ProjectsGrid from '@/components/ProjectsGrid';
import { getAllProjects } from '@/lib/airtable';

export const metadata: Metadata = {
  title: 'Projects - Chris Loidolt',
  description: 'Browse design and engineering projects in 3D printing, woodworking, and software development.',
};

export default async function ProjectsPage() {
  // Fetch projects at build/request time
  let projects: any[] = [];
  try {
    projects = await getAllProjects();
  } catch (error) {
    console.error('Error loading projects:', error);
  }

  return <ProjectsGrid projects={projects} />;
}

// src/routes/projects/+page.svelte
<script lang="ts">
  import ProjectsGrid from '$lib/components/ProjectsGrid.svelte';
  import type { PageData } from './$types';

  export let data: PageData;
</script>

<svelte:head>
  <title>Projects - {data.personSlug === 'loidolt' ? 'Loidolt Family' : data.personSlug}</title>
  <meta name="description" content="Browse design and engineering projects in 3D printing, woodworking, and software development." />
</svelte:head>

<ProjectsGrid projects={data.projects} />
