// src/components/PasswordModal.tsx
'use client';

import { useState } from 'react';

interface PasswordModalProps {
  locationName: string;
  onSubmit: (password: string) => void;
  onCancel: () => void;
  error?: string;
}

export default function PasswordModal({
  locationName,
  onSubmit,
  onCancel,
  error
}: PasswordModalProps) {
  const [password, setPassword] = useState('');

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    onSubmit(password);
  };

  return (
    <div
      style={{
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        zIndex: 2000,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
      }}
      onClick={onCancel}
    >
      <div
        style={{
          backgroundColor: 'var(--bg-surface)',
          border: '2px solid var(--border-color)',
          padding: '24px',
          maxWidth: '400px',
          width: '90%',
          boxShadow: '0 8px 24px rgba(0,0,0,0.3)',
        }}
        onClick={(e) => e.stopPropagation()}
      >
        <h2
          className="text-sm mb-2"
          style={{ color: 'var(--accent-secondary)' }}
        >
          Private Location
        </h2>

        <p
          className="text-sm mb-4"
          style={{ color: 'var(--text-muted)' }}
        >
          Enter password to view "{locationName}"
        </p>

        <form onSubmit={handleSubmit}>
          <input
            type="password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            placeholder="Password..."
            autoFocus
            className="input-terminal-primary mb-3"
          />

          {error && (
            <div
              className="text-xs mb-3"
              style={{ color: 'var(--error-color)' }}
            >
              {error}
            </div>
          )}

          <div style={{ display: 'flex', gap: '12px' }}>
            <button
              type="submit"
              className="flex-1 btn-terminal-primary"
            >
              [Unlock]
            </button>
            <button
              type="button"
              onClick={onCancel}
              className="flex-1 btn-terminal-muted"
            >
              [Cancel]
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}

// src/lib/components/PasswordModal.svelte
<script lang="ts">
  export let locationName: string;
  export let onSubmit: (password: string) => void;
  export let onCancel: () => void;
  export let error: string | undefined = undefined;

  let password = '';

  function handleSubmit(e: Event) {
    e.preventDefault();
    onSubmit(password);
  }

  function handleBackdropClick() {
    onCancel();
  }

  function handleModalClick(e: Event) {
    e.stopPropagation();
  }
</script>

<div
  class="fixed inset-0 z-[2000] flex items-center justify-center bg-black/50"
  on:click={handleBackdropClick}
  on:keydown={(e) => e.key === 'Escape' && onCancel()}
  role="dialog"
  aria-modal="true"
  tabindex="-1"
>
  <div
    class="w-[90%] max-w-md border-2 p-6 shadow-2xl"
    style="background-color: var(--bg-surface); border-color: var(--border-color)"
    on:click={handleModalClick}
    on:keydown={(e) => e.key === 'Enter' && handleSubmit(e)}
    role="button"
    tabindex="0"
  >
    <h2 class="mb-2 text-sm" style="color: var(--accent-secondary)">
      Private Location
    </h2>

    <p class="mb-4 text-sm" style="color: var(--text-muted)">
      Enter password to view "{locationName}"
    </p>

    <form on:submit={handleSubmit}>
      <input
        type="password"
        bind:value={password}
        placeholder="Password..."
        class="input-terminal-primary mb-3"
      />

      {#if error}
        <div class="mb-3 text-xs" style="color: var(--error-color)">
          {error}
        </div>
      {/if}

      <div class="flex gap-3">
        <button type="submit" class="btn-terminal-primary flex-1">
          [Unlock]
        </button>
        <button type="button" on:click={onCancel} class="btn-terminal-muted flex-1">
          [Cancel]
        </button>
      </div>
    </form>
  </div>
</div>
